<script type="text/javascript">
    //<![CDATA[[
    require(['jquery'], function($) {
           $(".vc-button").click(function(){
			  $(".vc-account-name").toggleClass("active");
			  $(".vc-account-main").toggleClass("active");
		});

		$('body').on('click', function (e) {
			if (!$('.vc-account-main').is(e.target)
				&& $('.vc-account-main').has(e.target).length === 0
				&& $('.vc-account-main.active').has(e.target).length === 0
			) {
				$('.vc-account-main').removeClass('active');
				$('.vc-account-name').removeClass('active');
			}

		});

    });

    // ]]>
</script>

<style>
.vc-account-main
{
	position: relative;
}
.vc-account-menu ul{
	margin: 0;
    padding: 0;
    list-style: none none;
    background: #fff;
    border: 1px solid #bbb;
    margin-top: 4px;
    min-width: 100%;
    z-index: 101;
    box-sizing: border-box;
    display: none;
    position: absolute;
    top: 100%;
    right: 0;
    box-shadow: 0 3px 3px rgb(0 0 0 / 15%);
	min-width: 175px;
    z-index: 1000;
}

@media (min-width: 768px){
.vc-account-header {
    min-width: 175px;
    z-index: 1000;
	display: inline-block;
}
.vc-account-menu ul li a
{
    color: #333333;
    text-decoration: none;
	display: block;
    line-height: 1.4;
    padding: 8px;
}
.vc-account-menu ul li{
	margin-bottom:0px;
}
.vc-account-menu  ul:before {
    right: 10px;
    top: -12px;
	border: 6px solid;
    border-color: transparent transparent #ffffff transparent;
    z-index: 99;
	content: '';
    display: block;
    height: 0;
    position: absolute;
    width: 0;
}
.vc-account-name .vc-button{
	background-image: none;
    background: none;
    -moz-box-sizing: content-box;
    border: 0;
    box-shadow: none;
    line-height: inherit;
    margin: 0;
    padding: 0;
    text-decoration: none;
    text-shadow: none;
    font-weight: 400;
    color: #ffffff;
	cursor: pointer;
    display: inline-block;
}
.vc-account-name.active .vc-button:after {
    content: '\e621';
}
.vc-account-name .vc-button:after {
	-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 10px;
    line-height: 22px;
    color: inherit;
    content: '\e622';
    font-family: 'luma-icons';
    margin: 0;
    vertical-align: top;
    display: inline-block;
    font-weight: normal;
    overflow: hidden;
    speak: none;
    text-align: center;
}
.vc-account-name .vc-button span{
	display:none;
}
.vc-account-header li:hover {
    background: #e8e8e8;
    cursor: pointer;
}
}
li.vc-account-main.active .vc-account-header
{
	display:block;
}
@media (max-width: 768px){
	.vc-account-name .vc-button{
		display:none;
	}
}
.header.content .logo img {
    width: auto !important;
}
</style>
