<?php

$author_type_name = ["Unkonw","Buyer","Seller","Voter"];
$order_id = $block->getData('order_id');
$customParameter = $block->getDetail();
$app_id = $customParameter['app_id'] ?? 0;
$voteCoinDecm = $customParameter['vote_coin_decm'] ?? 0;
$seller_wallet = $customParameter['seller_wallet'] ?? "";
$coin = $customParameter['coin'] ?? "";
$coin_symbol = $customParameter['coin_symbol'] ?? "";
$coin_decm = $customParameter['coin_decm'] ?? 0;
$order_status = $customParameter['order_status'] ?? 0;

$products = $customParameter['products'] ?? "";
$orderCurrencySymbol = $customParameter['orderCurrencySymbol'] ?? "";
$subTotal = $customParameter['subTotal'] ?? "";
$shippingAmount = $customParameter['shippingAmount'] ?? "";
$taxAmount = $customParameter['taxAmount'] ?? "";
$grandTotal = $customParameter['grandTotal'] ?? "";
$txHash     = $customParameter['tx_hash'] ?? "";
$chainOrderId   =   $customParameter['chain_order_id'] ?? 0;
$totalAmount = $customParameter['totalAmount'] ?? 0;
$paidAmount = $customParameter['paidAmount'] ?? 0;
$pendingAmount = bcsub($totalAmount, $paidAmount, 6);
$coinAmount = bcmul($totalAmount, pow(10, intval($coin_decm)));
//dispute
$voteArr = [
    0   =>  "Not Voted Yet",
    1   =>  "Agree Refund",
    2   =>  "Disagree Refund"
];
$modAId = $customParameter['moda_id'] ?? 0;
$modBId = ($customParameter['modb_id']==0)?"Not chosen yet":"#".$customParameter['modb_id'];
$modAVote = $voteArr[$customParameter['moda_vote']];
$modBVote = $voteArr[$customParameter['modb_vote']];
$refundAmount = $customParameter['refund'] ?? 0;
$disputeDiscuss = $customParameter['dispute_discuss'] ?? "";
$refundAmountDec = bcdiv($refundAmount, pow(10, intval($coin_decm)), 4);
$refundTime = $customParameter['refund_time'] ?? 0;
$disputeHash = $customParameter['dispute_hash'] ?? "No Transaction Yet";
$lastTxHash = $customParameter['last_tx_hash'] ?? "No Transaction Yet";
$dispute_status = $customParameter['dispute_status'] ?? 0;
//coin logs
$coinLogs = $customParameter['coinLogs'];
?>
<main id="site-content" role="main">
    <div class="cr-plugin-copy">
        <p>Copied</p>
    </div>
    <article class="post-8 page type-page status-publish hentry" id="post-8">
        <input type="hidden" id="coin" value="<?php echo $coin; ?>">
        <!-- <input type="hidden" id="expire_on"> -->
        <input type="hidden" id="current">
        <input type="hidden" id="imageBase" value="<?php echo $this->getViewFileUrl('Vbhex_Checkout::images'); ?>">
        <div class="post-inner thin ">
            <div class="entry-content">
                <div class="cr-plugin-main-box clearfix">
                    <div class="cr-plugin-left">
                        <div class="cr-plugin-billing-main cr-plugin-shadow">
                            <h3 class="cr-plugin-title">Mod Information</h3>
                            <div class="cr-plugin-timer" id="timerStatus"></div>
                            <div class="cr-plugin-billing-box">
                                <div class="cr-plugin-billing-amount">
                                    <ul>
                                        <li>
                                            <span> ModA Id : ModB Id : ModA Vote : ModB Vote</span>
                                             <p><?php echo "#".$modAId; ?> : <?php echo $modBId; ?> : <?php echo $modAVote; ?> : <?php echo $modBVote; ?> </p>
                                         </li>
                                        <li>
                                            <span>
                                                <?php if ($dispute_status == 7) : ?>
                                                    <input type="button" class="btn_agree" style="background-color:green" value="Agree" /> :
                                                    <input type="button" class="btn_disagree" style="background-color:red" value="Disgree" />
                                                <?php elseif ($dispute_status == 2) : ?>
                                                    <p><?php echo __("Refund Permitted By Voters"); ?></p>
                                                    <p class="copyToClipboard" style="font-size:12px;" title="click to copy" data-copy-detail="<?php echo $lastTxHash; ?>"><a class="last_tx_hash_link"></a> <img src="<?php echo $this->getViewFileUrl('Vbhex_Checkout::images/copy.png'); ?>"></p>
                                                <?php elseif ($dispute_status == 3) : ?>
                                                    <p><?php echo __("Refund Permitted By Seller"); ?></p>
                                                    <p class="copyToClipboard" style="font-size:12px;" title="click to copy" data-copy-detail="<?php echo $lastTxHash; ?>"><a class="last_tx_hash_link"></a> <img src="<?php echo $this->getViewFileUrl('Vbhex_Checkout::images/copy.png'); ?>"></p>
                                                <?php elseif ($dispute_status == 4) : ?>
                                                    <p><?php echo __("Refund Denied By Voters"); ?></p>
                                                    <p class="copyToClipboard" style="font-size:12px;" title="click to copy" data-copy-detail="<?php echo $lastTxHash; ?>"><a class="last_tx_hash_link"></a> <img src="<?php echo $this->getViewFileUrl('Vbhex_Checkout::images/copy.png'); ?>"></p>
                                                <?php else : ?>
                                                    <p><?php echo __("No Transaction Yet"); ?></p>
                                                <?php endif ?>
                                            </span>
                                            <p class="agree"><?php echo $agree; ?> : <?php echo $disagree; ?></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="cr-plugin-cart-summary cr-plugin-shadow cr-plugin-mr-top">
                            <h3 class="cr-plugin-title">Cart Summary</h3>
                            <div class="cr-plugin-cart-table">
                                <div class="cr-plugin-cart-table-box">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th>Product Info</th>
                                                <th style="text-align: center;">Quantity</th>
                                                <th style="text-align: right;">Price</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            if (is_array($products)) {
                                                foreach ($products as $product) {
                                            ?>
                                                    <tr>
                                                        <td style="width: 300px;">
                                                            <div class="cr-plugin-cart-img">
                                                                <img src="<?php echo $product['productImage']; ?>" align="">
                                                            </div>
                                                            <div class="cr-plugin-cart-des">
                                                                <p><?php echo $product['productName']; ?> <?php echo $product['productOptions']; ?></p>
                                                            </div>
                                                        </td>
                                                        <td style="text-align: center;">
                                                            <span><?php echo $product['productQty']; ?></span>
                                                        </td>
                                                        <td style="text-align: right;">
                                                            <span><?php echo $orderCurrencySymbol; ?> <?php echo $product['productPrice']; ?></span>
                                                        </td>
                                                    </tr>
                                            <?php
                                                }
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="cr-plugin-payment-detail">
                                <h3 class="cr-plugin-title">Payment Details</h3>
                                <ul>
                                    <li>Main Contract <span style="size: 15px;word-break: break-word;font-weight:500"><a class="main_contract_link"></a></span></li>
                                    <li>Seller Wallet <span style="size: 15px;word-break: break-word;font-weight:500"><?php echo $seller_wallet; ?></span></li>
                                    <li>Total <span><?php echo $orderCurrencySymbol; ?> <?php echo $subTotal; ?></span></li>
                                    <li>Shipping Fee <span><?php echo $orderCurrencySymbol; ?> <?php echo $shippingAmount; ?></span></li>
                                    <li>Total Taxes <span><?php echo $orderCurrencySymbol; ?> <?php echo $taxAmount; ?></span></li>
                                </ul>
                                <ul class="cr-plugin-payment-grand">
                                    <li>Grand Total <span><?php echo $orderCurrencySymbol; ?> <?php echo $grandTotal; ?></span></li>
                                </ul>
                            </div>
                        </div>
                        <div class="cr-plugin-billing-main cr-plugin-shadow">
                            <h3 class="cr-plugin-title">Order Coin Logs</h3>
                            <div class="cr-plugin-timer" id="timerStatus"></div>
                            <div class="cr-plugin-billing-box">
                                <div class="cr-plugin-billing-amount">
                                   <?php if($coinLogs): ?>
                                    <table>
                                        <?php foreach($coinLogs as $log): ?>
                                            <tr>
                                            <td><?= $block->simpleAddress($log->getUserWallet()) ?>  </td>
                                            <td><?= $block->escapeHtml($block->getScenariosLabel($log->getScenarios())) ?> </td>
                                            <td><?= /* @noEscape */ $log->getCoinAmount() ." ". $log->getCoinSymbol() ?> </td>
                                            <td><?= /* @noEscape */ $block->escapeHtml($log->getCreatedAt()) ?></p>
                                            </tr>
                                        <?php endforeach ?>
                                    </table>
                                        <br>
                                        <a target="_blank" href="<?= $block->escapeHtml($block->getLogUrl()) ?>">More</a>
                                   <?php else: ?>
                                    No Logs Yet
                                   <?php endif ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="cr-plugin-right">
                        <div class="cr-plugin-billing-main cr-plugin-shadow">
                            <h3 class="cr-plugin-title">Billing Details</h3>
                            <div class="cr-plugin-timer" id="timerStatus"></div>
                            <div class="cr-plugin-billing-box">
                                <!-- <div class="cr-plugin-billing-code">
                                 <img class="copyToClipboard" data-copy-detail= title="click to copy" align="">
                              </div> -->
                                <div class="cr-plugin-billing-amount">
                                    <ul>
                                        <li>
                                            <span>Amount : Paid Amount</span>
                                            <p><?php echo $totalAmount; ?> <?php echo $coin_symbol; ?> : <?php echo $paidAmount; ?> <?php echo $coin_symbol; ?></p>
                                        </li>
                                        <li>
                                            <span>Transaction Hash</span>
                                            <?php if ($order_status == 0) : ?>
                                                <p>No Transaction Yet</p>
                                            <?php elseif(strpos($txHash,'x')==1) : ?>
                                                <p class="copyToClipboard" style="font-size:12px;" title="click to copy" data-copy-detail="<?php echo $txHash; ?>"><a class="tx_hash_link"></a> <img src="<?php echo $this->getViewFileUrl('Vbhex_Checkout::images/copy.png'); ?>"></p>
                                            <?php else : ?>
                                                <p>No Transaction Yet</p>
                                            <?php endif ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="cr-plugin-billing-main cr-plugin-shadow">
                            <h3 class="cr-plugin-title">Dispute</h3>
                            <div class="cr-plugin-timer" id="timerStatus"></div>
                            <div class="cr-plugin-billing-box">
                                <div class="cr-plugin-billing-amount">
                                    <ul>
                                        <li>
                                            <span>Requested Amount : Refund End Time</span>
                                            <p class="refund_amount"><?php echo $refundAmountDec; ?> <?php echo $coin_symbol; ?> : <?php echo date('Y-m-d h:i:s', $refundTime); ?></p>
                                        </li>
                                        <li>
                                            <span>Dispute Hash</span>
                                            <?php if ($dispute_status == 0) : ?>
                                                <p>No Transaction Yet</p>
                                            <?php elseif(strpos($disputeHash,'x')==1) : ?>
                                            <p class="copyToClipboard" style="font-size:12px;" title="click to copy" data-copy-detail="<?php echo $disputeHash; ?>"><a class="dispute_hash_link"></a> <img src="<?php echo $this->getViewFileUrl('Vbhex_Checkout::images/copy.png'); ?>"></p>
                                            <?php else : ?>
                                                <p>No Transaction Yet</p>
                                            <?php endif ?>
                                        </li>
                                        <li>
                                            <span>Dispute Discussion</span>
                                            <?php if(is_array($disputeDiscuss)) : ?>
                                                <?php foreach($disputeDiscuss as $discuss) : ?>
                                                <div>
                                                    <p style="font-size:16px"><?= $author_type_name[$discuss['author_type']]; ?>: </p>
                                                    <span style="font-size:20px"><b><?= $block->escapeHtml($discuss['detail']); ?></b></span>
                                                    <p style="font-size:10px; margin: right 0;"><?= $discuss['created_at']; ?></p>
                                                </div>
                                                <?php endforeach; ?>
                                            <?php endif ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- .entry-content -->
        </div>
        <!-- .post-inner -->
    </article>
    <!-- .post -->
</main>
<script type="text/javascript">
    //<![CDATA[[
    require(['jquery', 'web3', 'constvar', 'chainvar'], function($, web3) {
        const ethEnabled = async () => {
            if (window.ethereum) {
                const accounts = await window.ethereum.request({
                    method: 'eth_requestAccounts'
                });

                window.web3 = new web3(window.ethereum);
                if (window.ethereum.networkVersion !== v_chainId) {
                    try {
                        await window.ethereum.request({
                            method: 'wallet_switchEthereumChain',
                            params: [{
                                chainId: web3.utils.toHex(v_chainId)
                            }]
                        });
                    } catch (err) {
                        // This error code indicates that the chain has not been added to MetaMask
                        if (err.code === 4902) {
                            await window.ethereum.request({
                                method: 'wallet_addEthereumChain',
                                params: [{
                                    chainName: v_chainName,
                                    chainId: web3.utils.toHex(v_chainId),
                                    nativeCurrency: {
                                        name: v_currencyName,
                                        decimals: v_decimals,
                                        symbol: v_currencySymbol
                                    },
                                    rpcUrls: [v_rpcUrl],
                                    blockExplorerUrls: [v_explorerUrl]
                                }]
                            });
                        }
                    }
                }
                const theAccount = window.web3.utils.toChecksumAddress(accounts[0]);
                const mainContractAddress = window.web3.utils.toChecksumAddress(v_mainContract);
                const mainContract = new window.web3.eth.Contract(abiJson, mainContractAddress);
                const voteCoinContractAddress = window.web3.utils.toChecksumAddress(v_voteCoinContract);
                const voteCoinContract = new window.web3.eth.Contract(erc20AbiJson, voteCoinContractAddress);
                var app_id = <?php echo $app_id; ?>;
                var chain_order_id = <?php echo $chainOrderId; ?>;
                var vote_price = <?php echo $votePrice; ?>;
                $('.btn_agree').click(function() {
                    voteCoinContract.methods.allowance(theAccount, mainContractAddress).call().then(function(result) {
                        if (window.web3.utils.toBN(result).lt(window.web3.utils.toBN(vote_price))) {
                            // approve allowance
                            voteCoinContract.methods.approve(mainContractAddress, 10 * window.web3.utils.toBN(vote_price)).send({
                                    from: theAccount
                                })
                                .then(function(receipt) {
                                    if (receipt.status) {
                                        agreeRefund();
                                    }
                                });
                        } else {
                            agreeRefund();
                        }
                    });
                });


                $('.btn_disagree').click(function() {
                    voteCoinContract.methods.allowance(theAccount, mainContractAddress).call().then(function(result) {
                        if (window.web3.utils.toBN(result).lt(window.web3.utils.toBN(vote_price))) {
                            // approve allowance
                            voteCoinContract.methods.approve(mainContractAddress, 10 * window.web3.utils.toBN(vote_price)).send({
                                    from: theAccount
                                })
                                .then(function(receipt) {
                                    if (receipt.status) {
                                        disagreeRefund();
                                    }
                                });
                        } else {
                            disagreeRefund();
                        }
                    });
                });

                var agreeRefund = function() {
                    // Refund now on blockchain
                    mainContract.methods.agreeRefund(app_id, chain_order_id).send({
                        from: theAccount
                    }).then(function(receipt) {
                        console.log(receipt);
                        window.setTimeout(() => {
                            window.location.href = window.location.href;
                        }, 30000);
                    });
                }

                var disagreeRefund = function() {
                    // Refund now on blockchain
                    mainContract.methods.disagreeRefund(app_id, chain_order_id).send({
                        from: theAccount,
                    }).then(function(receipt) {
                        console.log(receipt);
                        window.setTimeout(() => {
                            window.location.href = window.location.href;
                        }, 30000);
                    });
                }

                return true;
            }
            alert("Please install MetaMask to use this dApp!");
            return false;
        }

        $(document).ready(function() {

            // set main contract address
            $('.main_contract_link').html('<a target="_blank" href="'+v_explorerUrl+'address/'+v_mainContract+'">'+v_mainContract+'</a>');
            // set last tx hash
            $('.last_tx_hash_link').html('<a target="_blank" href="'+v_explorerUrl+'tx/<?php echo $lastTxHash; ?>"><?php echo $lastTxHash; ?></a>');
            // set dispute hash link
            $('.dispute_hash_link').html('<a target="_blank" href="'+v_explorerUrl+'tx/<?php echo $disputeHash; ?>"><?php echo $disputeHash; ?></a>');
            // set tx hash link
            $('.tx_hash_link').html('<a target="_blank" href="'+v_explorerUrl+'tx/<?php echo $txHash; ?>"><?php echo $txHash; ?></a>');
            if (window.ethereum) {
                ethEnabled();
                // refresh page every 30 seconds
                window.setTimeout( function() {
                    window.location.reload();
                }, 30000);
                // detect Metamask account change
                window.ethereum.on('accountsChanged', function(accounts) {
                    console.log('accountsChanges', accounts);
                    window.location.href = window.location.href;
                });

                // detect Network account change
                window.ethereum.on('networkChanged', function(networkId) {
                    console.log('networkChanged', networkId);
                    window.location.href = window.location.href;
                });
            } else {
                alert("Please install MetaMask to use this dApp!");
                $('.btn_agree').click(function() {
                    alert("Please install MetaMask to use this dApp!");
                });

                $('.btn_disagree').click(function() {
                    alert("Please install MetaMask to use this dApp!");
                });
            }

        })

    });
    // ]]>
</script>
